spring.application.name=Kody-JOBDAM

server.port=8088

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.error.include-message=always

# jwt.secret=${JWT_SIGN}
# jwt.access-token-expiration=${JWT_TIME}

jwt.secret=7fk2mQ9xLr8Vn4ZpT6cYw1HsDu3Be5Na
jwt.access-token-expiration=360000000

discord.bot.token=${DISCORD_BOT_TOKEN}
discord.bot.channel-id=${DISCORD_BOT_CHANNEL_ID}